Feat/chart color and tooltip
GouvernementFR/dsfr-chart pull request #19
Opened 2024-11-05 11:00 UTC by sebastienseenovate

2024-11-07 09:36 UTC, zellerbaptiste commented on src/utils.js
> +export const defaultColor = '#5C68E5';
```suggestion
export const defaultColor = categoricalPalette[0];
```

2024-11-07 09:38 UTC, zellerbaptiste commented on src/utils.js
> +export const defaultColor = '#5C68E5';
ou inversement dans le tableau `categoricalPalette` pour éviter la déclaration de la même valeur : 
`categoricalPalette[0] = defaultColor;`

2024-11-07 10:13 UTC, sebastienseenovate commented on src/utils.js
> +export const defaultColor = '#5C68E5';
Done

2024-11-07 13:59 UTC, zellerbaptiste requested changes
En attente des correctifs demandés par Jean et de notre review en Peer

2024-11-07 13:59 UTC, zellerbaptiste commented on src/components/Style/BarChart.scss
> +  }
Factoriser ce code CSS en commun dans tous les composants dans un fichier "tooltip.scss" et l'importer et/ou le surcharger par composant si besoin pour éviter de la duplication de code dans chaque fichier SASS de chaque composant.

2024-11-07 13:59 UTC, zellerbaptiste commented on src/components/Style/BarChart.scss
> +  }
Factoriser ce code CSS en commun dans tous les composants dans un fichier "rcol.scss" et l'importer et/ou le surcharger par composant si besoin pour éviter de la duplication de code dans chaque fichier SASS de chaque composant.

2024-11-07 13:59 UTC, zellerbaptiste commented on src/components/RadarChart.vue
> +    loadColors() {
Les méthodes `loadColors()` et `choosePalette()` peuvent-elles être factorisées dans le fichier "utils.js" et surchargées si besoin par composant ?

2024-11-08 09:15 UTC, sebastienseenovate commented on src/styles/components/componentsDsfr/barChart.scss
> +        background-color: #f6f6f6;
Done

2024-11-08 09:16 UTC, sebastienseenovate commented on src/styles/components/componentsDsfr/barChart.scss
> +        padding-bottom: 12px;
Done

2024-11-08 09:16 UTC, sebastienseenovate commented on src/components/Style/ScatterChart.scss
> +      width: 11.25rem;
Done

2024-11-08 09:17 UTC, sebastienseenovate commented on src/components/Style/BarChart.scss
> +  }
Done

2024-11-08 14:01 UTC, sebastienseenovate commented on src/components/RadarChart.vue
> +    loadColors() {
J'ai factorisé la methode choosePalette qui pour l'instant est la plus simple à faire.
Je vais regarder pour en faire de même sur la loadColors qui est plus personnelle au composant.
J'y travail

2024-11-14 15:40 UTC, zellerbaptiste requested changes

2024-11-14 16:49 UTC, zellerbaptiste requested changes

2024-11-14 16:49 UTC, zellerbaptiste commented on src/styles/components/componentsDsfr/barChart.scss
> +        background-color: #f6f6f6;
```suggestion
        background-color: var(--grey-975-75);
```

2024-11-14 16:49 UTC, zellerbaptiste commented on src/styles/components/componentsDsfr/lineChart.scss
>        background-color: #f6f6f6;
```suggestion
      background-color: var(--grey-975-75);
```

2024-11-14 16:49 UTC, zellerbaptiste commented on src/styles/components/componentsDsfr/pieChart.scss
>        // width: 100%;
A retirer

2024-11-14 16:49 UTC, zellerbaptiste commented on public/index.html
> +                  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>data-box</span>
A remplacer par l'exemple d'implementation du web-composant `<data-box>`

2024-11-15 12:31 UTC, zellerbaptiste approved these changes

2024-11-15 12:32 UTC, merged