Developpements suite aux retours
GouvernementFR/dsfr-chart pull request #2
Opened 2022-10-06 14:35 UTC by contitri

2022-10-13 15:36 UTC, zellerbaptiste commented on README.md
> +**DSFR Chart** doit être utilisé dans un projet utilisant le **DSFR**. Le projet doit à minima importer les feuilles css :
Ajouter le lien vers la documentation DSFR : https://www.systeme-de-design.gouv.fr/comment-utiliser-le-dsfr/developpeurs/prise-en-main-du-dsfr

2022-10-13 15:42 UTC, zellerbaptiste commented on package.json
>  {
ajouter une dependance de dev vers le DSFR et charger les ressources pour la page d'exemple depuis les node_modules

2022-10-18 13:39 UTC, zellerbaptiste requested changes
Merci pour les derniers commits de correction suite à nos retours,
dernière petite chose avant la validation de la PR, sur la page d'exemple il y a des erreurs en console à corriger : 
![Capture d’écran 2022-10-18 à 15 39 02](https://user-images.githubusercontent.com/10864245/196445871-54d05d6f-b246-4754-935f-8f80388b3746.png)

2023-11-06 14:10 UTC, zellerbaptiste reviewed
Quelques petites modifications du fichier README.md et ça sera bon pour le merge.

2023-11-06 14:10 UTC, zellerbaptiste commented on README.md
> +[Fichiers statiques](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/223019574/D+veloppeurs#Fichiers-statiques)
Ce lien est incorrect et doit être mis à jour.

2023-11-06 14:10 UTC, zellerbaptiste commented on README.md
> +<img src="./Pictures/ScatterChart.png" alt="ScatterChart" style="width:400px;"/>
Remplacer les sources des images par des liens absolus pour les afficher sur la page de présentation du package NPM : 
https://www.npmjs.com/package/dsfr-chart

2023-11-06 14:10 UTC, zellerbaptiste commented on README.md
> +Le processus de contribution est détaillé sur la page [CONTRIBUTING.md](CONTRIBUTING.md).
Remplacer le lien relatif par un lien absolu pour qu'il fonctionne sur la page de présentation du package NPM :
https://www.npmjs.com/package/dsfr-chart

2023-11-15 14:20 UTC, contitri commented on README.md
> +<img src="./Pictures/ScatterChart.png" alt="ScatterChart" style="width:400px;"/>
Je pense qu'une fois la PR mergée, les images devraient être affichées car elles renvoient actuellement vers le repo mais des fichiers qui n'existent pas.

2023-11-16 14:02 UTC, zellerbaptiste approved these changes

2023-11-16 14:02 UTC, merged