chore(dependencies): met a jour la version 1.11.1 du DSFR
GouvernementFR/dsfr-chart pull request #7
Opened 2024-02-08 09:33 UTC by zellerbaptiste

- monte la version du DSFR en 1.11.1
- met à jour la page de documentation
- met à jour les fichiers `README.md` et  `CONTRIBUTING.md`

2024-02-08 16:19 UTC, keryanS requested changes

2024-02-08 16:19 UTC, keryanS commented on README.md
> +<pie-chart x="[1, 2, 3]" , y="[10, 20, 30]"></pie-chart>
la virgule ?

2024-02-08 16:19 UTC, keryanS commented on README.md
> +    y="[[30, 10, 20], [10, 20, 30]]"
virgule

2024-02-08 16:19 UTC, keryanS commented on README.md
> +    ,
virgule

2024-02-08 16:23 UTC, zellerbaptiste commented on CONTRIBUTING.md
> -```npm install```
Dans `dsfr-chart` on utilise `npm` et pas `yarn` pour l'instant

2024-02-08 16:23 UTC, zellerbaptiste commented on CONTRIBUTING.md
>  Le **DSFR** est basé sur une architecture [NodeJS](https://nodejs.org/), il est donc nécessaire d’installer une version récente de nodeJs. Dans le terminal nous utiliserons les commandes de **npm**.
Dans `dsfr-chart` on utilise `npm` et pas `yarn` pour l'instant

2024-02-08 16:24 UTC, zellerbaptiste commented on CONTRIBUTING.md
>  Enfin, il est nécessaire de lancez un serveur local pour visualiser la page d'exemple index.html :
Il s'agit de la page d'exemple des charts de `dsfr-chart` et non du DSFR

2024-02-08 16:25 UTC, zellerbaptiste commented on CONTRIBUTING.md
> +Un serveur local sera alors lancé sur l'adresse localhost:8080. Accéder à http://localhost:8080 pour visualiser les exemples.
Il s'agit de la page d'exemple des charts de `dsfr-chart` et non du DSFR

2024-02-09 09:04 UTC, keryanS commented on CONTRIBUTING.md
>  Le **DSFR** est basé sur une architecture [NodeJS](https://nodejs.org/), il est donc nécessaire d’installer une version récente de nodeJs. Dans le terminal nous utiliserons les commandes de **npm**.
il s'agit de l'installation du dsfr ici

2024-02-09 09:23 UTC, zellerbaptiste commented on CONTRIBUTING.md
>  Le **DSFR** est basé sur une architecture [NodeJS](https://nodejs.org/), il est donc nécessaire d’installer une version récente de nodeJs. Dans le terminal nous utiliserons les commandes de **npm**.
non il s'agit du contributing au DSFR-chart

2024-02-12 14:24 UTC, keryanS approved these changes

2024-02-12 14:38 UTC, merged